// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFt5sSZ15T1jF8aZGUgKkCAiFi9ra-Opo',
    appId: '1:983068143451:web:47fe90c96d3dcb2986747e',
    messagingSenderId: '983068143451',
    projectId: 'fir-flutter-codelab-ccc92',
    authDomain: 'fir-flutter-codelab-ccc92.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-ccc92.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD46_wMKYUYI_ls5t2bMFEWfGoOcLNRjyo',
    appId: '1:983068143451:android:13633a76c856d37086747e',
    messagingSenderId: '983068143451',
    projectId: 'fir-flutter-codelab-ccc92',
    storageBucket: 'fir-flutter-codelab-ccc92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmhMC_yAM276afUy23-R5wrlJUGGOxXSA',
    appId: '1:983068143451:ios:8d59cb80324c30a486747e',
    messagingSenderId: '983068143451',
    projectId: 'fir-flutter-codelab-ccc92',
    storageBucket: 'fir-flutter-codelab-ccc92.appspot.com',
    iosClientId: '983068143451-5cl7c849aarfd95p7e15eg4lk23vb3sl.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmhMC_yAM276afUy23-R5wrlJUGGOxXSA',
    appId: '1:983068143451:ios:8d59cb80324c30a486747e',
    messagingSenderId: '983068143451',
    projectId: 'fir-flutter-codelab-ccc92',
    storageBucket: 'fir-flutter-codelab-ccc92.appspot.com',
    iosClientId: '983068143451-5cl7c849aarfd95p7e15eg4lk23vb3sl.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
